services:
  - type: web
    name: student-platform-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: student-platform-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: student-platform-redis
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_VISION_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false

databases:
  - name: student-platform-db
    databaseName: student_platform
    user: student_platform_user
    plan: free

services:
  - type: redis
    name: student-platform-redis
    plan: free
    maxmemoryPolicy: allkeys-lru